<a href="https://colab.research.google.com/github/vikasreddy2409/python/blob/main/Social_Media_Sentiments_Analysis_Dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#load the dataset
data=pd.read_csv('/content/sentimentdataset.csv')

In [ ]:
data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB

In [ ]:
data['Sentiment']

0       Positive
1       Negative
2       Positive
3       Positive
4       Neutral
          ...
727         Happy
728         Happy
729         Happy
730         Happy
731         Happy
Name: Sentiment, Length: 732, dtype: object

In [ ]:
data.groupby('User')[['Likes', 'Retweets']].mean()

                        Likes  Retweets
User
AbyssOfTime              45.0      22.0
AcceptanceSeeker         30.0      15.0
AdeleConcertGoer         80.0      40.0
AdeleMelodyTearjerker    60.0      30.0
AdventureAwaits          40.0      20.0
...                       ...       ...
YearbookExplorer         25.0      12.0
ZenLifestyle             30.0      15.0
ZenMaster                30.0      15.0
ZenMaster2               35.0      18.0
ZenSeeker                70.0      35.0

[685 rows x 2 columns]

In [30]:
data['total_engagement'] = data['Likes'] + data['Retweets']
print(data)

     Unnamed: 0.1  Unnamed: 0  \
0               0           0
1               1           1
2               2           2
3               3           3
4               4           4
..            ...         ...
727           728         732
728           729         733
729           730         734
730           731         735
731           732         736

                                                  Text    Sentiment  \
0     Enjoying a beautiful day at the park!        ...   Positive
1     Traffic was terrible this morning.           ...   Negative
2     Just finished an amazing workout! ðŸ’ª          ...   Positive
3     Excited about the upcoming weekend getaway!  ...   Positive
4     Trying out a new recipe for dinner tonight.  ...   Neutral
..                                                 ...          ...
727  Collaborating on a science project that receiv...       Happy
728  Attending a surprise birthday party organized ...       Happy
729  Successfully fundraising for a school charity ...       Happy
730  Participating in a multicultural festival, cel...       Happy
731  Organizing a virtual talent show during challe...       Happy

               Timestamp                                   User  Platform  \
0    2023-01-15 12:30:00                          User123            45.0
1    2023-01-15 08:45:00                          CommuterX          15.0
2    2023-01-15 15:45:00                          FitnessFan         60.0
3    2023-01-15 18:20:00                          AdventureX         23.0
4    2023-01-15 19:55:00                          ChefCook           37.0
..                   ...                                    ...       ...
727  2017-08-18 18:20:00       ScienceProjectSuccessHighSchool       59.0
728  2018-06-22 14:15:00            BirthdayPartyJoyHighSchool       73.0
729  2019-04-05 17:30:00   CharityFundraisingTriumphHighSchool       64.0
730  2020-02-29 20:45:00    MulticulturalFestivalJoyHighSchool       64.0
731  2020-11-15 15:15:00    VirtualTalentShowSuccessHighSchool       71.0

                                          Hashtags  Retweets  Likes  \
0        #Nature #Park                                  15.0   30.0
1        #Traffic #Morning                               5.0   10.0
2        #Fitness #Workout                              20.0   40.0
3        #Travel #Adventure                              8.0   15.0
4        #Cooking #Food                                 12.0   25.0
..                                             ...       ...    ...
727         #ScienceFairWinner #HighSchoolScience       20.0   39.0
728    #SurpriseCelebration #HighSchoolFriendship       25.0   48.0
729      #CommunityGiving #HighSchoolPhilanthropy       22.0   42.0
730         #CulturalCelebration #HighSchoolUnity       21.0   43.0
731   #VirtualEntertainment #HighSchoolPositivity       24.0   47.0

          Country  Year  Month  Day  Hour  total_engagement
0       USA        2023      1   15    12              45.0
1       Canada     2023      1   15     8              15.0
2     USA          2023      1   15    15              60.0
3       UK         2023      1   15    18              23.0
4      Australia   2023      1   15    19              37.0
..            ...   ...    ...  ...   ...               ...
727            UK  2017      8   18    18              59.0
728           USA  2018      6   22    14              73.0
729        Canada  2019      4    5    17              64.0
730            UK  2020      2   29    20              64.0
731           USA  2020     11   15    15              71.0

[732 rows x 16 columns]